#!/usr/bin/env python3


import rospy
from std_msgs.msg import Int16


# Récupération d'une nouvelle information
def callback(pose):
    print("Recois un nombre :", pose.data)


if __name__ == '__main__':
    # Initialisation du subscriber dans le noeud
    rospy.init_node('recoi_nombre')

    # Subscriber -> Listener -> Récupération d'information
    rospy.Subscriber('programme_nombre', Int16, callback)

    # Pour ne pas que le programme python se stop avant le noeud ROS
    rospy.spin()
