#!/usr/bin/env python3


import rospy
from turtlebot3_msgs.msg import Sound


# Test des publisher sur le buzzer du robot (on envoie une requête pour activer le buzzer)
if __name__ == '__main__':
    # Initialisation du noeud
    rospy.init_node('action_buzzer')

    # Publisher -> Sender -> Action sur le robot
    p = rospy.Publisher('sound', Sound, queue_size=10)
    rospy.sleep(5)

    # Activation du buzzer 
    p.publish(2) # Le chiffre '2' correspond au signal sonore qui est émis lorsque la batterie est faible

    # Pour pas que le programme python ne se stop avant le noeud ROS
    rospy.spin()
