#!/usr/bin/env python






import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import String
from std_msgs.msg import Float64
from turtlebot3_msgs.msg import Sound





#Test des publisher sur le buzzer du robot (on envoi une requette pour activer le buzzer)
if __name__ == '__main__':
    # Initialisation du noeud
    rospy.init_node('ActionDuRobot')

    # Publisher -> Sender -> Action sur le robot
    p = rospy.Publisher('sound', Sound, queue_size=10)


    # Activation du buzzer (bruit de battery faible)
    rospy.sleep(5)
    p.publish(2)

    # Activation du buzzer (bruit de ...)
    rospy.sleep(5)
    p.publish(2)

    #Pour pas que le python se stop avant le node
    rospy.spin()
