#!/usr/bin/env python3


import rospy
from std_msgs.msg import Int16


if __name__ == '__main__':
    # Initialisation du publisher dans le noeud
    rospy.init_node('EP')

    # Publisher -> Sender -> Envoi d'information
    p = rospy.Publisher('InfoDuRobot', Int16, queue_size=10)


    while True:
        p.publish(int(input("Envoi un nombre : ")))

    #Pour ne pas que le programme python se s'arrete avant le noeud
    rospy.spin()