#!/usr/bin/env python3


import rospy
from std_msgs.msg import Int16


# Recuperation d'une nouvelle information
def callback(pose):
    print("Reçois un nombre :",pose.data)


if __name__ == '__main__':
    # Initialisation du Subscriber dans le noeud
    rospy.init_node('recoi_nombre')

    # Subscriber -> Listener -> Recuperation d'information
    rospy.Subscriber('programme_nombre', Int16, callback)

    # Pour pas que le programme python ne se stop avant le noeud ROS
    rospy.spin()
